# Generated by Django 4.2.13 on 2024-05-22 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                ("place_id", models.AutoField(primary_key=True, serialize=False)),
                ("place_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PlaceKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.place"
                    ),
                ),
                (
                    "test_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.keyword"
                    ),
                ),
            ],
        ),
    ]
